var serve = {
  formcfg: {
    type: "object",
    properties: {
      group_all: {
        type: "object",
        "x-component": "card",
        properties: {
          UFORM_NO_NAME_FIELD0: {
            type: "object",
            "x-component": "card",
            "x-props": { title: null },
            properties: {
              author: {
                grouptitle: null,
                type: "GetLander",
                title: "下单人",
                required: true,
                "x-visible": true,
                "x-props": {
                  field_id: "author",
                  trigger_style: "no_trigger",
                  uform_para: null,
                },
              },
              currentdeptname: {
                grouptitle: null,
                type: "GetDepart",
                title: "部门",
                required: true,
                "x-visible": true,
                "x-props": {
                  field_id: "currentdeptname",
                  trigger_style: "no_trigger",
                  uform_para: null,
                },
              },
              adddate: {
                grouptitle: null,
                type: "GetDate",
                title: "下单日期",
                required: true,
                "x-visible": true,
                "x-props": {
                  field_id: "adddate",
                  trigger_style: "no_trigger",
                  uform_para: null,
                },
              },
              customerid: {
                grouptitle: "",
                type: "CustomerSelect",
                title: "",
                required: true,
                "x-visible": false,
                "x-props": {
                  field_id: "customerid",
                  trigger_style: "no_trigger",
                  uform_para: "",
                  disabled: true,
                },
              },
              phone: {
                grouptitle: null,
                type: "string",
                title: "联系电话",
                required: true,
                "x-visible": true,
                "x-props": {
                  field_id: "phone",
                  trigger_style: "no_trigger",
                  uform_para: null,
                },
              },
              linetype: {
                grouptitle: null,
                type: "assocselect",
                title: "线路类型",
                required: true,
                "x-visible": true,
                enum: [],
                "x-component": "assocselect",
                "x-props": {
                  level: "1",
                  api: "curd/getTableData",
                  basetable: "nanx_code_table",
                  filter_field: null,
                  associate_field: null,
                  trigger_group_uuid: "htT9Wyh1nV",
                  codetable_category_value: "线路类型",
                  label_field: "display_text",
                  value_field: "value",
                  query_cfg: {
                    level: "1",
                    api: "curd/getTableData",
                    basetable: "nanx_code_table",
                    filter_field: null,
                    associate_field: null,
                    trigger_group_uuid: "htT9Wyh1nV",
                    codetable_category_value: "线路类型",
                    label_field: "display_text",
                    value_field: "value",
                  },
                  ass_select_field_id: "linetype",
                  uform_para: null,
                },
              },
              bandwidth: {
                grouptitle: null,
                type: "number",
                title: "带宽（M）",
                required: true,
                "x-visible": true,
                "x-props": {
                  field_id: "bandwidth",
                  trigger_style: "no_trigger",
                  uform_para: null,
                },
              },
              image: {
                grouptitle: null,
                type: "fileuploader",
                title: "地图图片",
                required: false,
                "x-visible": true,
                "x-props": {
                  field_id: "image",
                  trigger_style: "no_trigger",
                  uform_para: null,
                },
              },
              requirementdescription: {
                grouptitle: null,
                type: "text_area",
                title: "需求描述",
                required: true,
                "x-visible": true,
                "x-props": {
                  field_id: "requirementdescription",
                  trigger_style: "no_trigger",
                  uform_para: null,
                },
              },
              isexternalrent: {
                grouptitle: "",
                type: "YesOrNo",
                title: "是否外租",
                required: false,
                "x-visible": true,
                "x-props": {
                  field_id: "isexternalrent",
                  trigger_style: "no_trigger",
                  uform_para: "",
                },
              },
            },
          },
        },
      },
    },
  },
};
module.exports = serve;
